source 'https://rubygems.org'
ruby '2.0.0'

gem 'json'
gem 'debugger'
gem 'builder'
gem 'nokogiri'
gem 'activesupport', '~> 4.0.2'
#gem 'ebay', :git => 'git://github.com/up_the_irons/ebay4r.git'
gem 'xmlparser'
gem 'soap2r'
